name: CI

on:
  pull_request:

jobs:
  build-and-test:
    name: build and test
    strategy:
      matrix:
        # note: we're using ubuntu-latest as a stand-in for all Linux
        # distributions. If we find we need more, we should do Docker stuff.
        os: [ubuntu-latest, macos-11]
    runs-on: "${{ matrix.os }}"
    steps:
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v18
      # - uses: cachix/cachix-action@v12
      #   with:
      #     name: tree-db
      #     authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'

      - run: nix build

  rustfmt:
    name: rustfmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v18
      # - uses: cachix/cachix-action@v12
      #   with:
      #     name: tree-db
      #     skipPush: true

      - run: nix develop --command cargo fmt --check
